#ifndef _CHAPTERMAP_H
#define _CHAPTERMAP_H

//A sort of decoder ring of sorts for OpenBible.info and WEB bible.

//Mapping from openbible.info to WEB bible chapters, and keep chapter order (order is openbible.info topic-votes)
// Note the order of these books matter, as OpenBible.info uses book number for some of it's metrics.

const char * BibleBooksCorrelation[] = {
	"Common Name", "OpenBible Short Name", "WEB Short name", "WEB Long Name", //Book #00 Is unused
	"Genesis", "Gen", "GEN", "﻿The First Book of Moses, Commonly Called Genesis.",
	"Exodus", "Exod", "EXO", "﻿﻿The Second Book of Mosis, Commonly Called Exodus.",
    "Leviticus", "Lev", "LEV", "﻿﻿The Third Book of Mosis, Commonly Called Leviticus.",
	"Numbers", "Num", "NUM", "﻿﻿The Fourth Book of Moses, Commonly Called Numbers.",
	"Deuteronomy", "Deut", "DEU", "﻿﻿The Fifth Book of Moses, Commonly Called Deuteronomy.",
	"Joshua", "Josh", "JOS", "﻿﻿The Book of Joshua.",
	"Judges", "Judg", "JDG", "﻿The Book of Judges.",
	"Ruth", "Ruth", "RUT", "﻿﻿The Book of Ruth.",
	"1 Samuel", "1Sam", "1SA", "﻿﻿The First Book of Samuel.",
	"2 Samuel", "2Sam", "2SA", "﻿The Second Book of Samuel.",
	"1 Kings", "1Kgs", "1KI", "﻿The First Book of Kings.",
	"2 Kings", "2Kgs", "2KI", "﻿The Second Book of Kings.",
	"1 Chronicles", "1Chr", "1CH", "﻿The First Book of Chronicles.",
	"2 Chronicles", "2Chr", "2CH", "﻿The Second Book of Chronicles.",
	"Ezra", "Ezra", "EZR", "﻿The Book of Ezra.",
	"Nehemiah", "Neh", "NEH", "﻿The Book of Nehemiah.",
	"Esther", "Esth", "EST", "﻿The Book of Esther.",
	"Job", "Job", "JOB", "﻿The Book of Job.",
	"Psalms", "Ps", "PSA", "﻿The Psalms.",
	"Proverbs", "Prov", "PRO", "﻿The Proverbs.",
	"Ecclesiastes", "Eccl", "ECC", "﻿Ecclesiates or, The Preacher.",
	"Song of Solomon", "Song", "SNG", "﻿The Song of Solomon.",
	"Isaiah", "Isa", "ISA", "﻿The Book of Isaiah.",
	"Jeremiah", "Jer", "JER", "﻿The Book of Jeremiah.",
	"Lamentations", "Lam", "LAM", "﻿The Lamentations of Jeremiah.",
	"Ezekiel", "Ezek", "EZK", "﻿The Book of Ezekiel.",
	"Daniel", "Dan", "DAN", "﻿The Book of Daniel.",
	"Hosea", "Hos", "HOS", "﻿The Book of Hosea.",
	"Joel", "Joel", "JOL", "﻿The Book of Joel.",
	"Amos", "Amos", "AMO", "﻿The Book of Amos.",
	"Obadiah", "Obad", "OBA", "﻿The Book of Obadiah.",
	"Jonah", "Jonah", "JON", "﻿The Book of Jonah.",
	"Micah", "Mic", "MIC", "﻿The Book of Micah.",
	"Nahum", "Nah", "NAM", "﻿The Book of Nahum.",
	"Habakkuk", "Hab", "HAB", "﻿The Book of Habakkuk.",
	"Zephaniah", "Zeph", "ZEP", "﻿The Book of Zephaniah.",
	"Haggai", "Hag", "HAG", "﻿The Book of Haggai.",
	"Zechariah", "Zech", "ZEC", "﻿The Book of Zechariah.",
	"Malachi", "Mal", "MAL", "﻿The Book of Malachi.",
	"Matthew", "Matt", "MAT", "﻿The Good News According to Matthew.",
	"Mark", "Mark", "MRK", "﻿The Good News According to Mark.",
	"Luke", "Luke", "LUK", "﻿The Good News According to Luke.",
	"John", "John", "JHN", "﻿The Good News According to John.",
	"Acts", "Acts", "ACT", "﻿The Acts of the Apostles.",
	"Romans", "Rom", "ROM", "﻿Paul’s Letter to the Romans.",
	"1 Corinthians", "1Cor", "1CO", "﻿﻿Paul’s First Letter to the Corinthians.",
	"2 Corinthians", "2Cor", "2CO", "﻿Paul’s Second Letter to the Corinthians.",
	"Galatians", "Gal", "GAL", "﻿Paul’s Letter to the Galatians.",
	"Ephesians", "Eph", "EPH", "﻿Paul’s Letter to the Ephesians.",
	"Philippians", "Phil", "PHP", "﻿Paul’s Letter to the Philippians.",
	"Colossians", "Col", "COL", "﻿Paul’s Letter to the Colossians.",
	"1 Thessalonians", "1Thess", "1TH", "﻿Paul’s First Letter to the Thessalonians.",
	"2 Thessalonians", "2Thess", "2TH", "﻿Paul’s Second Letter to the Thessalonians.",
	"1 Timothy", "1Tim", "1TI", "﻿Paul’s First Letter to Timothy.",
	"2 Timothy", "2Tim", "2TI", "﻿Paul’s Second Letter to Timothy.",
	"Titus", "Titus", "TIT", "﻿Paul’s Letter to Titus.",
	"Philemon", "Phil", "PHM", "﻿Paul’s Letter to Philemon.",
	"Hebrews", "Heb", "HEB", "﻿The Letter to the Hebrews.",
	"James", "Jas", "JAS", "﻿The Letter from James.",
	"1 Peter", "1Pet", "1PE", "﻿Peter’s First Letter.",
	"2 Peter", "2Pet", "2PE", "﻿Peter’s Second Letter.",
	"1 John", "1John", "1JN", "﻿John’s First Letter.",
	"2 John", "2John", "2JN", "﻿John’s Second Letter.",
	"3 John", "3John", "3JN", "﻿John’s Third Letter.",
	"Jude", "Jude", "JUD", "﻿The Letter from Jude.",
	"Revelation", "Rev", "REV", "﻿The Revelation to John.",
	//After this point are the apocraphyal books in the WEB
	"﻿Tobit", "", "TOB", "﻿﻿Tobit.",
	"Judith", "", "JDT", "﻿Judith.",
	"Esther (Greek)", "", "ESG", "﻿﻿Esther (Greek).",
	"Wisdom", "", "WIS", "﻿The Wisdom of Solomon.",
	"Sirach", "", "SIR", "﻿The Wisdom of Jesus the Son of Sirach, or Ecclesiasticus.",
	"﻿Baruch", "", "BAR", "﻿Baruch.",
	"1 Maccabees", "", "1MA", "﻿The First Book of the Maccabees.",
	"2 Maccabees", "", "2MA", "﻿The Second Book of the Maccabees.",
	"﻿1 Esdras", "", "1ES", "﻿1 Esdras.",
	"Manasses", "", "MAN", "﻿The Prayer of Manasses King of Judah when He was Held Captive in Babylon.",
	"Psalm 151", "", "PS2", "﻿Psalm 151.",
	"3 Maccabees", "", "3MA", "﻿The Third Book of the Maccabees.",
	"﻿2 Esdras", "", "2ES", "﻿2 Esdras.",
	"4 Maccabees", "", "4MA", "﻿The Fourth Book of the Maccabees.",
	"Daniel (Greek)", "", "DAG", "﻿The Book of Daniel with Greek Portions.",
	0, 0, 0, 0,
};


#endif

